service: spotify-social-listening

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:262634539124:table/SSL-Parties"

functions:
  create-party:
    handler: handler.createParty

  go-to-next-song:
    handler: handler.goToNextSong
